### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by patripo123** [NDUWRDC/LIMS#54] opened 2020-08-07 06:33 UTC
We need to add the quality control checks for the different procedures. I.e.  

Equipment/Test                                Quality Control
1. Samples                                        Temperature
2. Photometer                                   Blank test
3. Microbiology                                 Control test
4. Multi meter                              Calibration ( DO, Conductivity, pH)

Any more thoughts will be much appreciated

**Comment by davidNDU** [comment] 2020-09-04 09:14
**Samples Temperature**
It is possible to add temperature fields to the sample card. To record the temperature at the point of sampling makes sense. 
A logger could record the temperature of the sample during the transport. For this case tow fields could be added for minimum and maximum during transport and storage (e.g. fridge). 
What other temperatures are required? 
**Photometer Blank test** and **Microbiology Control test**
As I understand this is part of a specific procedure and the QC manual has to ensure this. I don't think a specific task like this should be part recorded to te LIMS. 
**Multi meter Calibration** or any other calibration
This is related to feature request (enhancement) #7

**Comment by davidNDU** [comment] 2021-02-04 15:06
All questions answered except for the temperatures.
Duplicate of #81

**Closed by davidNDU** 2021-02-04 15:06 UTC
Labels: documentation
